language: clojure
sudo: required
lein: lein
dist: xenial
script: lein do clean, javac, test
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: ${HEROKU_KEY}
  app: gh-commits-category
